"""Add is_verified field to users table

Revision ID: f880f1f0801c
Revises: 4c40f9edc3d8
Create Date: 2024-12-07 18:17:00.346470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f880f1f0801c"
down_revision: Union[str, None] = "4c40f9edc3d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "tokens", ["id"])
    
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=True))
    
    op.execute("UPDATE users SET is_verified = FALSE WHERE is_verified IS NULL")
    
    op.alter_column("users", "is_verified",
                    existing_type=sa.Boolean(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified")
    op.drop_constraint(None, "tokens", type_="unique")
    # ### end Alembic commands ###
