"""Remove token field from users table

Revision ID: 8a064291765d
Revises: 87f20187f020
Create Date: 2024-12-07 18:02:42.516918

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a064291765d"
down_revision: Union[str, None] = "87f20187f020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
